// app/signup/page.tsx
// GigOS — Sign up page (Step 2 of the build order: Auth)
//
// Flow:
// 1. User fills form (name, email, password, role)
// 2. Supabase Auth creates the account (auth.users)
// 3. We insert a matching row into our own `users` table, using the
//    same id Supabase gave us, so the two stay in sync (per the note
//    at the bottom of schema.prisma)

'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

export default function SignUpPage() {
  const router = useRouter()
    const supabase = createClient()

      const [name, setName] = useState('')
        const [email, setEmail] = useState('')
          const [password, setPassword] = useState('')
            const [role, setRole] = useState<'worker' | 'employer'>('worker')
              const [error, setError] = useState<string | null>(null)
                const [loading, setLoading] = useState(false)

                  async function handleSubmit(e: React.FormEvent) {
                      e.preventDefault()
                          setError(null)
                              setLoading(true)

                                  // Step 1: create the Supabase Auth user
                                      const { data: authData, error: authError } = await supabase.auth.signUp({
                                            email,
                                                  password,
                                                      })

                                                          if (authError) {
                                                                setError(authError.message)
                                                                      setLoading(false)
                                                                            return
                                                                                }

                                                                                    const userId = authData.user?.id
                                                                                        if (!userId) {
                                                                                              setError('Sign up succeeded but no user id was returned. Try logging in.')
                                                                                                    setLoading(false)
                                                                                                          return
                                                                                                              }

                                                                                                                  // Step 2: create the matching profile row in our own `users` table.
                                                                                                                      // NOTE: role isn't stored on the User table yet (schema doesn't have
                                                                                                                          // a role field yet) — for now we just create the profile. We'll add
                                                                                                                              // a role/type field to the schema before the "post a gig" page, since
                                                                                                                                  // that page needs to know who's allowed to post.
                                                                                                                                      const { error: profileError } = await supabase.from('users').insert({
                                                                                                                                            id: userId,
                                                                                                                                                  email,
                                                                                                                                                        name,
                                                                                                                                                            })

                                                                                                                                                                if (profileError) {
                                                                                                                                                                      setError(`Account created, but profile setup failed: ${profileError.message}`)
                                                                                                                                                                            setLoading(false)
                                                                                                                                                                                  return
                                                                                                                                                                                      }

                                                                                                                                                                                          setLoading(false)
                                                                                                                                                                                              router.push('/dashboard')
                                                                                                                                                                                                }

                                                                                                                                                                                                  return (
                                                                                                                                                                                                      <div style={{ maxWidth: 400, margin: '60px auto', padding: '0 20px' }}>
                                                                                                                                                                                                            <h1 style={{ fontSize: 24, fontWeight: 700, marginBottom: 8 }}>
                                                                                                                                                                                                                    Create your GigOS account
                                                                                                                                                                                                                          </h1>
                                                                                                                                                                                                                                <p style={{ color: '#666', marginBottom: 24 }}>
                                                                                                                                                                                                                                        Find local gigs, or post one. Quick pay, no waiting weeks.
                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                    <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
                                                                                                                                                                                                                                                            <label>
                                                                                                                                                                                                                                                                      Name
                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                            type="text"
                                                                                                                                                                                                                                                                                                        required
                                                                                                                                                                                                                                                                                                                    value={name}
                                                                                                                                                                                                                                                                                                                                onChange={(e) => setName(e.target.value)}
                                                                                                                                                                                                                                                                                                                                            style={inputStyle}
                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                              </label>

                                                                                                                                                                                                                                                                                                                                                                      <label>
                                                                                                                                                                                                                                                                                                                                                                                Email
                                                                                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                                                                                      type="email"
                                                                                                                                                                                                                                                                                                                                                                                                                  required
                                                                                                                                                                                                                                                                                                                                                                                                                              value={email}
                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={inputStyle}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Password
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        minLength={6}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={inputStyle}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <fieldset style={{ border: '1px solid #ddd', borderRadius: 8, padding: 12 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <legend style={{ fontSize: 13, color: '#666' }}>I'm signing up as a...</legend>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <label style={{ marginRight: 16 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="radio"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  name="role"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                checked={role === 'worker'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={() => setRole('worker')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />{' '}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Worker (looking for gigs)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="radio"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  name="role"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                checked={role === 'employer'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={() => setRole('employer')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />{' '}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Employer (posting gigs)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </fieldset>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p style={{ color: '#c0392b', fontSize: 14, margin: 0 }}>{error}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: '12px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: 8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        background: '#111',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: '#fff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontWeight: 600,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cursor: loading ? 'not-allowed' : 'pointer',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        opacity: loading ? 0.6 : 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {loading ? 'Creating account...' : 'Sign up'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const inputStyle: React.CSSProperties = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          display: 'block',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            width: '100%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              padding: '10px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginTop: 4,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: '1px solid #ccc',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        boxSizing: 'border-box',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }